// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArNJ9FGaWoM6EZ9L4YyYDd5zlybAdR120',
    appId: '1:184885743498:web:77c80b291ddbcfd1318273',
    messagingSenderId: '184885743498',
    projectId: 'skill-link47',
    authDomain: 'skill-link47.firebaseapp.com',
    storageBucket: 'skill-link47.firebasestorage.app',
    measurementId: 'G-XJ2NCVD3RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwjAW44OP0586rnfEU7L2yXNFU5jTxIl4',
    appId: '1:184885743498:android:7896cab48256382c318273',
    messagingSenderId: '184885743498',
    projectId: 'skill-link47',
    storageBucket: 'skill-link47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtgbsPfHvIZDCCPMS6KKhh-yvU_fO94cw',
    appId: '1:184885743498:ios:ff534932835c82fc318273',
    messagingSenderId: '184885743498',
    projectId: 'skill-link47',
    storageBucket: 'skill-link47.firebasestorage.app',
    iosBundleId: 'com.example.plumberProject',
  );
}
